{%- if cookiecutter.ingress == 'yes' -%}
{{ "{{" }}- if not .Values.isCanary -{{ "}}" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ "{{" }} .Release.Name {{ "}}" }}
  labels:
    helm.sh/chart: {{ "{{" }} .Chart.Name {{ "}}" }}-{{ "{{" }} .Chart.Version | replace "+" "_" {{ "}}" }}
    app.kubernetes.io/name: {{ "{{" }} .Release.Name {{ "}}" }}
    app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
    app.kubernetes.io/managed-by: {{ "{{" }} .Release.Service {{ "}}" }}
  {{ "{{" }}- with .Values.ingress.labels {{ "}}" }}
    {{ "{{" }}- toYaml . | nindent 6 {{ "}}" }}
  {{ "{{" }}- end {{ "}}" }}
  annotations:
  {{ "{{" }}- with .Values.ingress.annotations {{ "}}" }}
    {{ "{{" }}- toYaml . | nindent 4 {{ "}}" }}
  {{ "{{" }}- end {{ "}}" }}
  {{ "{{" }}- range .Values.ingress.hosts {{ "}}" }}
    external-dns.alpha.kubernetes.io/hostname: {{ "{{" }} cat "" .host | replace " " "" {{ "}}" }}
  {{ "{{" }}- end {{ "}}" }}
spec:
{{ "{{" }}- if .Values.ingress.tls {{ "}}" }}
  tls:
  {{ "{{" }}- range .Values.ingress.tls {{ "}}" }}
    - hosts:
      {{ "{{" }}- range .hosts {{ "}}" }}
        - {{ "{{" }} cat "" . | replace " " "" {{ "}}" }}
      {{ "{{" }}- end {{ "}}" }}
      secretName: {{ "{{" }} .secretName {{ "}}" }}
  {{ "{{" }}- end {{ "}}" }}
{{ "{{" }}- end {{ "}}" }}
  rules:
  {{ "{{" }}- range .Values.ingress.hosts {{ "}}" }}
    - host: {{ "{{" }} cat "" .host | replace " " "" {{ "}}" }}
      http:
        paths:
        {{ "{{" }}- range .paths {{ "}}" }}
          - path: {{ "{{" }} . {{ "}}" }}
            backend:
              serviceName: {{ "{{" }} $.Release.Name {{ "}}" }}
              servicePort: http
        {{ "{{" }}- end {{ "}}" }}
  {{ "{{" }}- end {{ "}}" }}
{{ "{{" }}- end {{ "}}" }}
{% endif -%}
